In [ ]:
'''
This notebook contains the code to merge all male data across the years based on sections.
There are datasets for 2012, 2012-1.5, 2013 and 2014
The different sections that will be merged are as follows:
**2012**
1. Cover
2. Roaster
3. Section 1: Education (All men 18 and above)
4. Section 2: Agriculture
5. Section 3: Assets
6. Section 4: Consumption and Expenditure
7. Section 5: Credit
8. Section 6: Employment and Income
9. Section 7: Economic Events/Shocks
10. Section 8: Community Participation and Social Network Membership

**2013**
1. Cover
2. Roaster
3. Section 1: Education: Males 19 years and older
4. Section 2: Agriculture
5. Section 3: Assets
6. Section 4: Consumption and Expenditure
7. Section 5: Credit
8. Section 6: Employment and Income
9. Section 7: Health
10. Section 8: Political Participation and Governance

**2014**
1. Cover
2. Roaster
3. Section 1: Education: Males 19 years and older
4. Section 2: Agriculture
5. Section 3: Assets
6. Section 4: Consumption and Expenditure
7. Section 5: Credit
8. Section 6: Employment and Income
9. Section 7: Economic Events/Shocks‚Äù
10. Section 8: Participation in Social Safety Net
11. Section 9: Siblings
12. Section 10: Transfers
13. Section 11: Health and Nutrition

'''

In [ ]:
'''
All files in the male folder will be converted to xlsx format for readability
This will be done for all male files across the years
'''

import pandas as pd
import glob

# Path where the .dta files are located
# We will use just once cell for each conversion since just the path is changing
folder_path = r'C:\Users\warra\Downloads\data\data\2014_data\Male'

# Get a list of all .dta files in the specified directory
file_list = glob.glob(folder_path + '/*.dta')

# Loop through the list of files
for file in file_list:
    # Read the .dta file into a pandas DataFrame
    df = pd.read_stata(file, convert_categoricals=False)
    
    # Define the output file name by replacing .dta with .xlsx
    output_file = file.replace('.dta', '.xlsx')
    
    # Write the DataFrame to an Excel file
    df.to_excel(output_file)

In [ ]:
'''
The following code block will merge all roaster files across the years.
* First, we are going to read the respective files and store them as data frames
* Next, we are going to define column mappings that I have already figured out via manual methods
* Once the mappings are done per the set rules, we will see the new roaster dataset across the years 1.
'''

In [55]:
# This code block stores file paths to variables to make the code neat
# The stored variables are called in the read_excel function and stored as dataframes

import pandas as pd

# Store excel file locations to variables (change it as per your path to file)
edu_2012=r"C:\Users\warra\Desktop\Freelance\data\data\MaleMerge\2. Section 1 Education\2012_s1p1_m.xlsx"
edu_2012_5=r"C:\Users\warra\Desktop\Freelance\data\data\MaleMerge\2. Section 1 Education\2012_1.5_edu.xlsx"
edu_2013=r"C:\Users\warra\Desktop\Freelance\data\data\MaleMerge\2. Section 1 Education\2013_s1_m.xlsx"
edu_1_2014=r"C:\Users\warra\Desktop\Freelance\data\data\MaleMerge\2. Section 1 Education\2014_s1p1_m.xlsx"
edu_2_2014=r"C:\Users\warra\Desktop\Freelance\data\data\MaleMerge\2. Section 1 Education\2014_s1p2_m.xlsx"

# Read excel files
df_2012 = pd.read_excel(edu_2012)
df_2012_5 = pd.read_excel(edu_2012_5)
df_2013 = pd.read_excel(edu_2013)
df_1_2014 = pd.read_excel(edu_1_2014)
df_2_2014 = pd.read_excel(edu_2_2014)

In [56]:
'''
This code block will be used to standardize column names across the years to avoid discrepancies during the merging process.
For example in the roaster data for 2013 rq21 and rq23 are not the same as rq21 and rq23 in 2014 data, but they have the same variable names. Hence, we decide to rename such columns beforehand
We will add the updated name to the mapping dictionaries instead of the original names.

'''

# Rename columns in df_2012
df_2012.rename(columns={
    'pid' : 'r_pid', 
    'S1Q3': 's1p1_q2', 
    'S1Q4': 's1p1_q3',
    'S1Q5': 's1p1_q4',
    'S1Q6': 's1p1_q5',
    'S1Q7': 's1p1_q7',
    'S1Q8': 's1p1_q9',
    'S1Q9': 's1p1_q10',
    'S1Q10': 's1p1_q11',
    'S1Q11': 's1p1_q12',
    'S1Q15': 's1p1_q13',
    'S1Q12': 'Rep_class',
    'S1Q14': 'Day_Missed_sch12',
    'S1Q13' : 'Dis_No_sch',
}, inplace=True)

# Rename columns in df_2012_5
df_2012_5.rename(columns={
    'Round' : 'round',
    'PID1' : 'r_pid',
    'Q2': 's1p1_q2',
    'Q3' : 's1p1_q3',
    'Q4': 's1p1_q4',
    'Q5': 's1p1_q5',
    'Q6': 's1p1_q13',
    'Q8_12M': 'Day_Missed_sch12',
    'Q8_24M': 'Day_Missed_sch24',
    'Q7': 'Dis_No_sch'
}, inplace=True)

# Rename columns in df_2013
df_2013.rename(columns={
    's1_q2': 's1p1_q2',
    's1_q3': 's1p1_q3',
    's1_q4':'s1p1_q4',
    's1_q5':'s1p1_q5',
    's1_q6':'s1p1_q6',
    's1_q7':'s1p1_q7',
    's1_q8':'s1p1_q9',
    's1_q9' : 's1p1_q10',
    's1_q10':'s1p1_q11',
    's1_q11':'s1p1_q12',
    's1_q12' : 'Rep_class',
    's1_q13' : 'Day_Missed_sch12',
    's1_q14' : 's1p1_q13'
}, inplace=True)

# df_2014 doesn't need renaming as it is the reference

In [57]:
df_2014 = pd.concat([df_1_2014, df_2_2014], ignore_index=True)

In [ ]:
print(df_2014)

In [58]:
# Define the column mappings based on the provided positions
# Make dictionaries for each year with updated names
# replace with 'None' where there are no columns


mapping_2012 = [
    'hid', 'round', 'r_pid', 's1p1_q2', 's1p1_q3', 's1p1_q4', 's1p1_q5', None, 's1p1_q7', None, 
    's1p1_q9', 's1p1_q10', 's1p1_q11', 's1p1_q12', 's1p1_q13', 'Rep_class', 'Day_Missed_sch12', 
    'Dis_No_sch', None, None, None, None, None, None, None, None, None, None, None, None, None, 
    None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None
]

mapping_2012_5 = [
    'hid', 'round', 'r_pid', 's1p1_q2', 's1p1_q3', 's1p1_q4', 's1p1_q5', None, None, None, None, 
    None, None, None, 's1p1_q13', None, 'Day_Missed_sch12', 'Dis_No_sch', 'Day_Missed_sch24', 
    'C_PROVINCE', 'C_DISTRICT', 'C_TEHSIL', 'C_UC', 'C_MOUZA', 'C_HH_NUM', None, None, None, None, 
    None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None
]

mapping_2013 =  [
    'hid', 'round', 'r_pid', 's1p1_q2', 's1p1_q3', 's1p1_q4', 's1p1_q5', 's1p1_q6', 's1p1_q7', None, 
    's1p1_q9', 's1p1_q10', 's1p1_q11', 's1p1_q12', 's1p1_q13', 'Rep_class', 'Day_Missed_sch12', None, 
    None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 
    None, None, None, None, None, None, None, None, None, None, None
]

mapping_2014 = [
    'hid', 'round', 'r_pid', 's1p1_q2', 's1p1_q3', 's1p1_q4', 's1p1_q5', 's1p1_q6', 's1p1_q7', 
    's1p1_q8', 's1p1_q9', 's1p1_q10', 's1p1_q11', 's1p1_q12', 's1p1_q13', None, None, None, None, 
    None, None, None, None, None, None, 's1p2_q1', 's1p2_q2', 's1p2_q3', 's1p2_q4', 's1p2_q5', 
    's1p2_q6a', 's1p2_q6b', 's1p2_q6c', 's1p2_q7a', 's1p2_q7b', 's1p2_q7c', 's1p2_q7d', 's1p2_q7e', 
    's1p2_q7f', 's1p2_q8', 's1p2_q9', 's1p2_q10', 's1p2_q11', 's1p2_q12', 's1p2_q13', 's1p2_q14'
]

In [64]:
# Create a list of all possible columns in the correct order
all_columns = []
for col in mapping_2012:
    if col and col not in all_columns:
        all_columns.append(col)
for col in mapping_2012_5:
    if col and col not in all_columns:
        all_columns.append(col)
for col in mapping_2013:
    if col and col not in all_columns:
        all_columns.append(col)
for col in mapping_2014:
    if col and col not in all_columns:
        all_columns.append(col)

In [65]:
def standardize_and_merge(dfs, mappings, all_columns):
    merged_data = {col: [] for col in all_columns}

    for df, mapping in zip(dfs, mappings):
        for i, col in enumerate(mapping):
            if col:
                ref_col = col
                if col in df.columns:
                    merged_data[ref_col].extend(df[col].tolist())
                else:
                    merged_data[ref_col].extend([np.nan] * len(df))
    
    max_len = max(len(v) for v in merged_data.values())
    for key in merged_data:
        col_len = len(merged_data[key])
        if col_len < max_len:
            merged_data[key].extend([np.nan] * (max_len - col_len))

    merged_df = pd.DataFrame.from_dict(merged_data)
    merged_df = merged_df.loc[:, ~merged_df.columns.str.contains('Unnamed')]
    return merged_df

In [66]:
# Example usage with your dataframes and mappings
dfs = [df_2012, df_2012_5, df_2013, df_2014]
mappings = [mapping_2012, mapping_2012_5, mapping_2013, mapping_2014]

merged_df = standardize_and_merge(dfs, mappings, all_columns)

In [62]:
# Save the merged dataframe to a CSV file


merged_df.to_csv('merged_Section_1.csv', index=False)

In [67]:
# Rename columns for the merged file (if needed)
rename_mapping = {
    'hid': 'HID',
    'round': 'Survey_Round',
    'r_pid': 'PID',
    's1p1_q2': 'Read',
    's1p1_q3': 'Write',
    's1p1_q4': 'add_sub',
    's1p1_q5': 'attend_sch',
    's1p1_q6': 'Res_Not_Attend',
    's1p1_q7': 'type_sch',
    's1p1_q8': 'Medium',
    's1p1_q9': 'Age_start_sch',
    's1p1_q10': 'Still_Attend_sch',
    's1p1_q11': 'Age_Stop_sch',
    's1p1_q12': 'Res_Stop_sch',
    's1p1_q13': 'H_class'

    # Add other renaming mappings as needed
}

merged_df.rename(columns=rename_mapping, inplace=True)

# Save the merged dataframe to a CSV file
merged_df.to_csv('merged_Section_1.csv', index=False)